builds:
  - id: sigma-esf
    binary: sigma-esf
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

brews:
  -
    tap:
      owner: bradleyjkemp
      name: homebrew-formulae
    homepage: "https://github.com/bradleyjkemp/sigma-esf"
    description: "Run Sigma rules against EndpointSecurity Framework events."

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
    format: zip

snapshot:
  name_template: "{{ .Tag }}-next"
